"""made changes in pipe/data modesl and added pipe_data model 

Revision ID: 1bcbc289c977
Revises: c1f6a21e848e
Create Date: 2026-09-30 00:12:11.789203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcbc289c977'
down_revision: Union[str, Sequence[str], None] = 'c1f6a21e848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pipline_DataSource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['DataSource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Pipline_DataSource_id'), 'Pipline_DataSource', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pipline_DataSource_id'), table_name='Pipline_DataSource')
    op.drop_table('Pipline_DataSource')
    # ### end Alembic commands ###
