"""create pipeline runs table

Revision ID: 5b8871e1fd5d
Revises: 1102caecebf2
Create Date: 2026-09-26 23:02:36.808592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b8871e1fd5d'
down_revision: Union[str, Sequence[str], None] = '1102caecebf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'Pipeline_Runs',

        sa.Column(
            'id',
            sa.Integer(),
            nullable=False
        ),

        sa.Column(
            'pipeline_id',
            sa.Integer(),
            nullable=False
        ),

        sa.Column(
            'status',
            postgresql.ENUM(
                'PENDING',
                'RUNNING',
                'SUCCESS',
                'FAILED',
                'CANCELLED',
                name='pipelinestatus',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column(
            'started_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False
        ),

        sa.Column(
            'finished_at',
            sa.DateTime(),
            nullable=True
        ),

        sa.Column(
            'duration',
            sa.Float(),
            nullable=True
        ),

        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True
        ),

        sa.ForeignKeyConstraint(
            ['pipeline_id'],
            ['Pipelines.id']
        ),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_Pipeline_Runs_id'),
        'Pipeline_Runs',
        ['id'],
        unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f('ix_Pipeline_Runs_id'),
        table_name='Pipeline_Runs'
    )

    op.drop_table('Pipeline_Runs')

    # ### end Alembic commands ###