"""added email in employee table

Revision ID: 65b6d607fe33
Revises: f0fbe88028f4
Create Date: 2026-09-24 21:24:41.960331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b6d607fe33'
down_revision: Union[str, Sequence[str], None] = 'f0fbe88028f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Employees', 'email')
    # ### end Alembic commands ###
