"""created data source model

Revision ID: b11b64645278
Revises: 5b8871e1fd5d
Create Date: 2026-09-27 22:41:21.764466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11b64645278'
down_revision: Union[str, Sequence[str], None] = '5b8871e1fd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataSource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('CSV', 'POSTGRESQL', 'REST_API', 'MINIO', name='datasourcetype'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DataSource_id'), 'DataSource', ['id'], unique=False)
    op.create_index(op.f('ix_DataSource_name'), 'DataSource', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DataSource_name'), table_name='DataSource')
    op.drop_index(op.f('ix_DataSource_id'), table_name='DataSource')
    op.drop_table('DataSource')
    # ### end Alembic commands ###
