"""updated data source model

Revision ID: c1f6a21e848e
Revises: b11b64645278
Create Date: 2026-09-27 23:30:38.166993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f6a21e848e'
down_revision: Union[str, Sequence[str], None] = 'b11b64645278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataSource', sa.Column('configuration', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataSource', 'configuration')
    # ### end Alembic commands ###
