"""changed the value type in the dataQuatlityresultmodel

Revision ID: d7ca2952c21f
Revises: c86357148f5d
Create Date: 2026-10-07 20:39:30.575958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ca2952c21f'
down_revision: Union[str, Sequence[str], None] = 'c86357148f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DataQualityResult', 'rows_affected',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DataQualityResult', 'rows_affected',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
