"""create pipelines table

Revision ID: f972c06544d0
Revises: 65b6d607fe33
Create Date: 2026-09-26 02:28:40.138149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f972c06544d0'
down_revision: Union[str, Sequence[str], None] = '65b6d607fe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='pipelinestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Pipelines_id'), 'Pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_Pipelines_name'), 'Pipelines', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pipelines_name'), table_name='Pipelines')
    op.drop_index(op.f('ix_Pipelines_id'), table_name='Pipelines')
    op.drop_table('Pipelines')
    # ### end Alembic commands ###
